version: '2.2'
services:
 openelevationservice:
  network_mode: "host"
  image: uaveditor/openelevationservice:0.2.1-uav
  volumes:
  - /var/scripts/openelevationservice/data:/deploy/app/tiles
  ports:
   - "5020:5000"
  mem_limit: 28g